Add auto-incrementing tokenId, totalSupply functions.  Cleaned up tests and code
neodaoist/1729w pull request #7
Opened 2022-08-23 20:57 UTC by plaird523

2022-08-24 19:01 UTC, neodaoist requested changes

2022-08-24 19:45 UTC, plaird523 commented on src/1729Essay.sol
>  contract OneSevenTwoNineEssay is Ownable, ERC721, ERC2981 {
Discussed in standup.  Using the ERC2981 implementation from OpenZepplin, confirmed by unit tests

2022-08-24 19:45 UTC, plaird523 commented on src/1729Essay.sol
>  import {ERC721URIStorage} from "openzeppelin-contracts/token/ERC721/extensions/ERC721URIStorage.sol";
Good catch

2022-08-24 19:48 UTC, plaird523 commented on src/1729Essay.sol
> +        return tokenId;
Seems unnecessary if the return statement is the last line of the function body, but if it makes you happier I'll add it :grinning:

2022-08-24 19:50 UTC, plaird523 commented on test/1729Essay.t.sol
> +        vm.startPrank(multisig);
I like to put the expectation of failure as close to the line that's expected to cause the failure as the framework allows (the line right before in this case).  I think that makes it more clear what's going on when you maintain the test.

All other changes made.

2022-08-25 19:07 UTC, neodaoist approved these changes
LGTM

2022-08-25 19:07 UTC, merged